[build]
  command = "npm run build"
  publish = "dist"

# Also build the web component
[build]
  command = "npm run build && npm run build:component"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"